### ISSUE TITLE
Can the SLAM be applied to the environment where height is changing

### ISSUE THREAD

**Issue by Flandoe** [koide3/hdl_graph_slam#109]
I have a 16-line lidar which is  perpendicular to the ground and collect data from the stairs environment. It cannot correctly generate the map and I use the hdl_graph_slam_400.launch. Are there some advices for me to improve the performance? Thanks for your work.

**Comment by koide3** [comment]
Hi @Flandoe ,
It would be better to use GICP instead of NDT for a 16-line LIDAR. See the parameter tuning guide for more details. 
https://github.com/koide3/hdl_graph_slam#parameter-tuning-guide
