### ISSUE TITLE
Using IMU with hdl_graph_slam

### ISSUE THREAD

**Issue by ekow-mensah** [koide3/hdl_graph_slam#11]
Hi, Please I would like to ask if I was to implement the hdl_graph_slam algorithm with a mobile robot will it be possible to integrate an IMU to work with the algorithm or use odometry? Also i would like to ask what is the differences between the various launch files (that is,  hdl_graph_slam.launch, hdl_graph_slam_400.launch, hdl_graph_slam_500.launch and hdl_graph_slam_ford.launch) ?

**Comment by koide3** [comment]
For now, we cannot use IMU and odometry for hdl_graph_slam. It estimates the sensor motion from only range data. But, yes, we can improve the algorithm (in particular scan matching and graph optimization) with such information, and I want to do it someday.

The launch files are tuned for different environments (400: indoor, 500: outdoor, ford: outdoor with GPS). You can see example environments in README.

**Comment by ekow-mensah** [comment]
Ahhh I see thank you. Do you reckon including IMU data and odometry will be challenging to implement?

**Comment by koide3** [comment]
No, theoretically, it is not so difficult, and I already have some code for the integration of IMU and scan matching for another project (hdl_graph_slam). Just time is needed...

**Comment by ekow-mensah** [comment]
Ahhh okay thank you very much for the help I really appreciate it.

**Comment by weisongwen** [comment]
hi @koide3 , thanks for sharing your work. The IMU acceleration is integrated into the graph optimization. however, the bias for IMU is not estimated yet?

**Comment by GLKode** [comment]
Hi @koide3 , @weisongwen @ekow-mensah 
hdl_graph_slam is mainly using odometry data (in keyframes, scan matching, ..), I would like to use the IMU instead of the odometer data, or maybe both together, could you please give me some hints how this is possible and which classes, nodelets to be changed? do we need to implement IMU wherever odometer is used? 
Thank you.
