### ISSUE TITLE
a small question about the article

### ISSUE THREAD

**Issue by FishInWave** [koide3/hdl_graph_slam#133]
On page 6 of your article —— “A Portable 3D LIDAR-based System for Long-term and Wide-area People Behavior Measurement”, there is a sentence like this, "In order to deal with this problem, we integrate the NDT scan matching with angular velocity data provided by the 3D LIDAR using Unscented Kalman filter"。
I wonder that the mentioned "angular velocity data " are obtained from other INS sensor or estimated with lidar pointcloud data?

**Comment by koide3** [comment]
We used an embedded INS in HDL32e to obtain angular velocity data.
