### ISSUE TITLE
Improving loop closure for large drift

### ISSUE THREAD

**Issue by nyangshawbin** [koide3/hdl_graph_slam#136]
Hi, 

I would like to get some advice on tuning the parameters especially for loop closure for large drifts. I am running SLAM offline on a rosbag recorded from Gazebo. Loop closure seems to be working well for me for small drifts as shown in the first picture below. However, for larger drift, as shown in second pic, the loop closure was not good. 

![hdl_graph_slam_first_good_loop_closure](https://user-images.githubusercontent.com/55438554/87323034-cb814380-c560-11ea-96e9-38a2a9483fa5.png)
![hdl_graph_slam_improper_loop_closure](https://user-images.githubusercontent.com/55438554/87323352-3cc0f680-c561-11ea-9e76-d068b4905f2e.png)

I have tried increasing the `<param name="distance_thresh" value="15.0" />` to increase the loop closure search window to correct larger drifts but the result was instead sub-optimal as improper loop closure was done. Hence would like to ask if there are other parameters which i can tune to improve the loop closure performance, or if im doing something wrong here. Thank you in advance! Following are more information about my setup/launch file.

Setup:
Lidar: HDL-32E
[hdl_graph_slam_400 launch file](https://github.com/nyangshawbin/outdoor_slam/blob/master/hdl_graph_slam/launch/hdl_graph_slam_400.launch)

**Comment by koide3** [comment]
The loop closing implementation is very basic and limited, and suffer from large drift like the one in your case. If you're going to do outdoor mapping, I recommend using a GPS that greatly helps to close large loops at outdoor.

**Comment by nyangshawbin** [comment]
Hi, thanks for getting back. I see, i will consider that advice then thanks once again!
