### ISSUE TITLE
issues about system resource utilization.

### ISSUE THREAD

**Issue by CAKGOD** [koide3/hdl_graph_slam#141]
Hi! I'm testing the performance of this framework. I found that in the background process, _prefiltering_, _scan_ matching_ and _hdl_ graph_ process takes up less resources, while _velodyne_nodelet_manager_ process takes up most resources, including CPU and memory. Can you help me to explain why this happens. Of course, frameworks succeed for the dataset.
Thank u~

**Comment by srinivasrama** [comment]
@CAKGOD how you solved the issue?
