### ISSUE TITLE
error in rviz

### ISSUE THREAD

**Issue by weisongwen** [koide3/hdl_graph_slam#16]
hi @koide3  
when I run my own bag file, the tf transform between the odom and the keyframe/velodyne seems to have not been published. do you have any suggestion on this?  
![image](https://user-images.githubusercontent.com/24927996/41387658-aba119b2-6fba-11e8-94da-77c703317608.png)

best 
welson

**Comment by koide3** [comment]
@weisongwen ,
It sometimes happens when the program couldn't process data real-time. Please try to use bag_player.py or play your bag at a slow speed.

**Comment by weisongwen** [comment]
Dear @koide3 ,
thanks for your information,
best 
welson

**Comment by caoyifeng001** [comment]
@weisongwen hello how to solve it ,i have same problem.

**Comment by weisongwen** [comment]
as @koide3  mentioned, play your bag at a slow spped.
