### ISSUE TITLE
pose graph optimization  error

### ISSUE THREAD

**Issue by autoperson** [koide3/hdl_graph_slam#17]
Hi ,I already install g2o with hdl_graph_slam branch ,but when pose graph optimization , it has problem with [velodyne_nodelet_manager-2] process has died [pid 4467, exit code -11, cmd /opt/ros/kinetic/lib/nodelet/nodelet manager __name:=velodyne_nodelet_manager , am I need set g2o dir in cmakelist?

**Comment by autoperson** [comment]
and can I get your paper?  please send to autoperson@qq.com

**Comment by mameng1** [comment]
I also need your paper,can you send your paper to 2908071445@qq.com

**Comment by sysuequal** [comment]
I have the same problem that the [velodyne_nodelet_manager-1] process has died

**Comment by koide3** [comment]
Did you try the ways in #4 ? In particular, try docker.

Regarding the paper, I think I can send you it if you tell me your official address in your institute or organization.

**Comment by mameng1** [comment]
@koide3,hello,I am a student in xidian' university ,Xian,China,my email is qmma@stu.xidian.edu.cn

**Comment by mameng1** [comment]
@koide3,hello,I am a student in xidian' university ,Xian,China,my email is qmma@stu.xidian.edu.cn,thank you

**Comment by autoperson** [comment]
I don't find the problem again , may be I adjust optimize iterations param

**Comment by autoperson** [comment]
I set the iteration param with 512

**Comment by koide3** [comment]
@autoperson ,
Thanks for the information. I'll try the setting...

**Comment by ekow-mensah** [comment]
@autoperson Where did you set the iteration param?? In the launch files? or the actual code?

**Comment by autoperson** [comment]
It was the number of  g2o optimization iterations in code @ekow-mensah, you can find other answers of 4# question.
