### ISSUE TITLE
trajectory coordiante frame

### ISSUE THREAD

**Issue by GLKode** [koide3/hdl_graph_slam#171]
Hi @koide3 ,

are the messages published on /odom topic the resulted trajectory of hd graph slam? and what coordinate frame are they?

**Comment by koide3** [comment]
```/odom``` topic publishes "odometry" data without loop and floor constraints. It's origin is the very first frame of the LiDAR data, and may have some estimation drift.

**Comment by GLKode** [comment]
Thanks @koide3 for the reply,so on which topic the end trajectory including all constraints such as loops and floor points ia published?

**Comment by koide3** [comment]
The corrected trajectory is not be published. But, you can use tf lookup to find the latest sensor pose in the map coordinate.

**Comment by GLKode** [comment]
thanks @koide3 for the reply. so even if I collect the poses, the jumps in the trajectory would correct the error in the previous poses with the loop closure and change the positions of the poses. do you know how a function can be implemented to generate a trajectory at the end when the map is complete, considering all contains, gps/imu, floor points, loops and lidar/odom ? so that at the end you have a pcd file and a trajectory file. 

you use the markers to create a trajectory in rviz, can this be further developed for this purpose ?

**Comment by koide3** [comment]
To obtain the final estimation result of the trajectory, you can use the ```dump``` service that saves the final pose graph with all constraints. Note that the pose graph has only keyframe poses, and thus poses of some frames would be missing. To recover the full sensor trajectory, you would need to do some smoothing on the optimized keyframe poses.

**Comment by GLKode** [comment]
Thank you @koide3 will try that, what about the hdl_localization how can i get the final trajectory there? can you give me a hint about that also please?

**Comment by koide3** [comment]
Since hdl_localization publishes map aligned poses, you can just subscribe to ```/odom``` topic to get the final trajectory.

**Comment by GLKode** [comment]
Thank you @koide3 for the information :)
