### ISSUE TITLE
how to perform path planning on the 3d .pcd map?

### ISSUE THREAD

**Issue by darshb34** [koide3/hdl_graph_slam#172]
Is there a way to save the obtained .pcd map into a grid map? 

I want to use the hdl_graph_slam with movebase(or move_base_flex) NavStack for my wheeled segway robot. How would I perform path planning like Navfn ros and DWA. 

Thank you

**Comment by koide3** [comment]
This repo would be a help: https://github.com/koide3/pointcloud_to_2dmap
