### ISSUE TITLE
covariance of the g2o optimzation

### ISSUE THREAD

**Issue by DarrenWong** [koide3/hdl_graph_slam#174]
We want to evaluate the g2o optimization result, try to add the below code to compute the covariance of the last keyframe refer to  https://github.com/RainerKuemmerle/g2o/blob/4b9c2f5b68d14ad479457b18c5a2a0bce1541a90/g2o/examples/target/static_target.cpp#L107
The GTSAM have a similar [interface](https://github.com/borglab/gtsam/blob/3f3e286a4dcbf161f2f5dc143cbb6a352c1cc1a9/examples/OdometryExample.cpp#L92) will have a fine result. 
But the covariance matrix computed by g2o seems not correct as it is smaller as time goes on.

Do you have any suggestions if we want to get the covariance of last keyframe after g2o optimization?

add code after https://github.com/koide3/hdl_graph_slam/blob/b1d9b51020e705a5c33bd9e1b1ec523781f93782/apps/hdl_graph_slam_nodelet.cpp#L582
```
   g2o::SparseBlockMatrix<Eigen::MatrixXd> spinv;

    graph_slam->computeMarginals(spinv, keyframe->node)
    g2o::SparseBlockMatrix<Eigen::MatrixXd>::SparseMatrixBlock* b = spinv.blockCols()[spinv.blockCols().size()-1].begin()->second;
    auto inverse_b = b->inverse();
    std::cout << "covariance\n" << spinv << std::endl;
    std::cout<< inverse_b<<std::endl; 
    
```
the result at the beginning
![image](https://user-images.githubusercontent.com/5771106/104716136-71a54480-5762-11eb-90e2-84b10974528b.png)

the result  after a few state( 400+), the covariance of the pose(the diagonal) is very small
![image](https://user-images.githubusercontent.com/5771106/104717657-9a2e3e00-5764-11eb-8130-d43c03c68c41.png)

**Comment by koide3** [comment]
The covariance can be gets smaller after closing some loops and adding some other constraints (e.g., GPS). I've not tried to obtain marginals with g2o, and I'm not really sure, but I think your result may be correct.

**Comment by DarrenWong** [comment]
Thanks for your reply. But it seems too small... std 0.0009 if represents the translation. Is it possible the top-left (3x3) is the rotation std and the right bottom(3x3) is the translation std?

**Comment by koide3** [comment]
I got it. It's in the form of information matrix. You can take the inverse of it to get the distribution.

http://docs.ros.org/en/fuerte/api/re_vision/html/structg2o_1_1SparseOptimizer.html#a501617cdf217f9f50d16de939af46855

**Comment by DarrenWong** [comment]
Yes

> I got it. It's in the form of information matrix. You can take the inverse of it to get the distribution.
> 
> http://docs.ros.org/en/fuerte/api/re_vision/html/structg2o_1_1SparseOptimizer.html#a501617cdf217f9f50d16de939af46855

Yes I have already inverted the output as the output is the information matrix. . But the result of inverse's std is very small 0.0009.... 
` auto inverse_b = b->inverse();`

**Comment by DarrenWong** [comment]
thanks this should be ok to recover the covariance, might be I assume the top left 3x3 belongs to the rotation should be fine~

**Comment by DarrenWong** [comment]
Sorry for the late reply. You might need to change to sparse_opt solver to use the computeMarginals. You can refer to the git diff as shown below.

![image](https://user-images.githubusercontent.com/5771106/182103155-76d38db1-6e06-4c72-8639-c6221fe2b3d3.png)

**Comment by ahmedadamji** [comment]
> Sorry for the late reply. You might need to change to sparse_opt solver to use the computeMarginals. You can refer to the git diff as shown below.
> 
> ![image](https://user-images.githubusercontent.com/5771106/182103155-76d38db1-6e06-4c72-8639-c6221fe2b3d3.png)

Thank you so much Darren, this worked for me, do you also have any idea how i can access the individual covariences of observed points passed into keyframes?

**Comment by DarrenWong** [comment]
Might be you can refere to the code here for GICP point's covariance. https://github.com/PointCloudLibrary/pcl/blob/4766f4146b792ef833c773d35157fcc9c668110b/registration/include/pcl/registration/gicp.h#L388
or revise PCL's [getFitnessScore](https://pointclouds.org/documentation/classpcl_1_1_registration.html#ab26742c383b6f5e86fb96a236fb08728) to check the residual of the corresponding points.

**Comment by ahmedadamji** [comment]
> Might be you can refere to the code here for GICP point's covariance. https://github.com/PointCloudLibrary/pcl/blob/4766f4146b792ef833c773d35157fcc9c668110b/registration/include/pcl/registration/gicp.h#L388 or revise PCL's [getFitnessScore](https://pointclouds.org/documentation/classpcl_1_1_registration.html#ab26742c383b6f5e86fb96a236fb08728) to check the residual of the corresponding points.

Thank you Darren!
