### ISSUE TITLE
Question: Using slam while starting with a preknown map

### ISSUE THREAD

**Issue by wienans** [koide3/hdl_graph_slam#177]
Hi, is it possible to use this SLAM with a pre known map and to extend this map. 
E.g doing a first drive with the this slam running and at a later point in time i want to localize and extend the map again after setting a initial position.

Greetings
Sven

**Comment by koide3** [comment]
While this package does not support extending existing maps, our another package [interactive_slam](https://github.com/SMRT-AIST/interactive_slam/wiki/Example3) could be help in merging multiple mapping results.

**Comment by wienans** [comment]
Okay thank you for your answer
