### ISSUE TITLE
data collection equipment

### ISSUE THREAD

**Issue by DamonMIN** [koide3/hdl_graph_slam#18]
Dear,
    Can you introduce your data collection equipment? What do the "rostopic gpsimu_driver/gpstime gpsimu_driver/imu_data gpsimu_driver/temperature" mean?

**Comment by koide3** [comment]
Hi @DamonMIN ,
I used Garmin GPS (which comes bundled with HDL32e) and [*gps_imu* branch of *velodyne_driver*](https://github.com/ros-drivers/velodyne/tree/gps_imu). The topics publish IMU and GPS data, and you can subscribe them from velodyne_driver.
