### ISSUE TITLE
Accuracy of the map

### ISSUE THREAD

**Issue by ikhann** [koide3/hdl_graph_slam#180]
Hello!
Thanks for this awesome framework!

Could you advise please.
How can achieve such accuracy of the outdoor map to have a single layer of ground (one surface) without doubled ground or "thick film" of the ground?

Thank you!

**Comment by koide3** [comment]
I think enabling floor constraint helps in resolving the doubled ground issue.

**Comment by ikhann** [comment]
@koide3 Thank you for your reply!

Is it correct to enable "floor detection" option for an outdoor map with a road slope with ascents and descents?

**Comment by koide3** [comment]
The floor plane correction assumes that the environment has a flat floor. If you need to consider ascents/descents or multiple floors, please consider using [interactive_slam](https://github.com/SMRT-AIST/interactive_slam) that enables manually inserting plane constraints to the map.

**Comment by ikhann** [comment]
I've already started using it. 
Thanks a lot!
