### ISSUE TITLE
Porting to ROS2

### ISSUE THREAD

**Issue by ikhann** [koide3/hdl_graph_slam#189]
Hi, @koide3
Thank you for this awesome framework! 
I would like to interest do you have any thoughts about porting this project to ROS2?

Best, Daniil.

**Comment by koide3** [comment]
Maybe I will not, because I'm developing a new SLAM framework and reducing the effort to maintain this package. But, if there are many requests, I'll consider porting to ROS2.

**Comment by ikhann** [comment]
Thank you for your response! May consider you already have one request 😁

**Comment by Timple** [comment]
So this makes people curious! What's the new SLAM framework?

**Comment by vico1999-ros** [comment]
ROS2 version is expected!!

**Comment by ikhann** [comment]
> ROS2 version is expected!!

Really? Where is a proof? 🙂
