### ISSUE TITLE
Failed to use my own .bag data for mapping

### ISSUE THREAD

**Issue by sunmiaozju** [koide3/hdl_graph_slam#19]
Hi, we can run the example *.bag data to build the map correctly, but there is something wrong when i am using my own *.bag data. (i use a velodyne-vlp16). Here are the details:

i use the command to record my own *.bag:

`roslaunch velodyne_pointcloud VLP16_points.launch [calibration:=/home/smartcar/sunm/velodyne/VeloView-VLP-16-HiRes.yaml] `

`rosbag record -O indoor /velodyne_points `

does this is right to save my own *.bag data ? thanks a lot

when i using my own  *.bag data , i got the error message in the rviz:
![screenshot from 2018-06-25 21-48-04](https://user-images.githubusercontent.com/34623535/41854065-d8b929d4-78c1-11e8-9c4a-13be50c14235.png)

and, i got the error message ine the terminal:

![screenshot from 2018-06-25 21-48-20](https://user-images.githubusercontent.com/34623535/41854035-cc01fc84-78c1-11e8-99f3-c024130acd95.png)

and in the rviz, i only get the motionless point, it seems like it only show one frame:

![screenshot from 2018-06-25 22-32-54](https://user-images.githubusercontent.com/34623535/41856457-becd9c52-78c7-11e8-99e4-c0fb297bff5b.png)

it seems that there is something wrong in the time of the data recorded according to the error mssage in the rviz. But i don't know how to deal with it ? Would help me with it? thanks a lot!

**Comment by koide3** [comment]
Hi @sunmiaozju ,
When you played your bag, did you added --clock option? like:
```bash
rosbag play --clock ***.bag
```
Without this option, tf cannot handle timestamps in a bag properly.

**Comment by sunmiaozju** [comment]
Thank you for your answer.  But i indeed use the --clock option to output the timestamps. 

I think if the equipment (i am using velodyne-vlp16) is not suitable for the code, because i find that the example bag is from velodyne HDL32e.

can we only use the velodyne-vlp16 for the code? Thanks a lot!

**Comment by koide3** [comment]
Hi @sunmiaozju ,
We've tested this package with VLP16 as well. But, it could be unstable compared to HLD32e, since it has a narrow field of view and provide fewer points. I think you have to move the sensor slowly.

To check if the scan matching is working, change "Fixed Frame" on rviz to "odom". You'll be able to see the odometry estimated by the matching.
