### ISSUE TITLE
g2o version

### ISSUE THREAD

**Issue by YoshuaNava** [koide3/hdl_graph_slam#2]
Hi,
I tried to use the latest version of g2o, `4d23d59f52fe9ed08805bb9183bbf5d2bddfc782`, but the definitions of Vector2D, Vector3D and Vector4D used by hdl_graph_slam were replaced by a templated type, VectorN<dim> ([reference](https://github.com/RainerKuemmerle/g2o/blob/master/g2o/core/eigen_types.h#L49)). I added back the type definitions required by this pkg, but got a memory leak when creating the optimizer. Hence, I could not run hdl_graph_slam_nodelet.

**Fix**
I fetched g2o commit `a48ff8c42136f18fbe215b02bfeca48fa0c67507`, built and ran the algorithm without any new incidences.

Hope this helps,
Yoshua

**Comment by koide3** [comment]
Hi,
Thank you for letting me know the change on g2o and the quick fix. I added an instruction to install the specified g2o commit instead of the latest one to README. 
I've not figured out what causes this problem yet... But, I'll fix it and make this package be able to cope with the latest g2o.
