### ISSUE TITLE
Compatible with Livox mid 40

### ISSUE THREAD

**Issue by ManChrys** [koide3/hdl_graph_slam#209]
Hello, 

i would like to ask if this package is compatible with livox lidar. I am using it on RS Lidar and VLP lidar and im very pleased.

If someone did it plese let me know.

Thanks in advance guys.

**Comment by koide3** [comment]
It is somehow compatible with any range sensors. But, you would need to change some parameters, and the performance would not be very good compared to packages dedicated to such sensors.

**Comment by ManChrys** [comment]
hi @koide3 !!

ok i see !! Thank you a lot my friend.
