### ISSUE TITLE
please help. hdl_graph_slam launch nodelet issue

### ISSUE THREAD

**Issue by lidarmansiwon** [koide3/hdl_graph_slam#260]
hi, i using this package in jetson orin and noetic, 20.04
so when i launch "roslaunch hdl_graph_slam hdl_graph_slam.launch 
I got that error msg. I need your help. please help me,,,

![2023-07-19_01-21](https://github.com/koide3/hdl_graph_slam/assets/117976120/ef41b33e-536c-433f-89e7-e8b71c895723)

**Comment by Guoc0529** [comment]
Hi, have you resolved this issue? I’m facing the same problem as well.

**Comment by lidarmansiwon** [comment]
@Guoc0529 Hello! I don't remember the details but I split up the workspace and proceeded with sourcing and ran it and it worked!

**Comment by Guoc0529** [comment]
> @Guoc0529 Hello! I don't remember the details but I split up the workspace and proceeded with sourcing and ran it and it worked!你好！我不记得细节了，但我把工作区分开了，然后开始采购和运行它，它奏效了！
thanks！
I don’t quite understand, and I hope you can explain a bit more in detail
