### ISSUE TITLE
Multi-floor situation

### ISSUE THREAD

**Issue by ShenZehong** [koide3/hdl_graph_slam#39]
Hi, the output is not well optimized when dealing with multi-floor laser data. Can you give me some advice on fixing it? You know, after stepping upstairs, everything goes wrong.

**Comment by koide3** [comment]
Hi @ShenZehong ,
Currently, the floor plane constraint assumes a single floor environment. Could you try to set enable_floor_detection to false?

**Comment by ShenZehong** [comment]
Many thanks for your reply, however it didn't work. We're planning to update our sensors. It's really a big problem.
