### ISSUE TITLE
Running time? 

### ISSUE THREAD

**Issue by antithing** [koide3/hdl_graph_slam#44]
Hi, and thank you for making this code available.
What is the latency of this system roughly? 
How many scans can be processed per second in real time? 
Thanks!

**Comment by koide3** [comment]
The SLAM system consists of frontend (scan matching odometry, low latency & high frequency) and backend (pose graph optimization, high latency & low frequency) moduels. The processing speed depends on the computer spec and parameters. On my environment, the frontend runs at about 100 fps, while the backend runs ones every 5sec.

**Comment by antithing** [comment]
thank you!
