### ISSUE TITLE
saved pcd doesn't have intensities.

### ISSUE THREAD

**Issue by donrv** [koide3/hdl_graph_slam#51]
Hi,
Is there any way to save Intensity values while saving pcd files?

**Comment by koide3** [comment]
Hi @donrv ,
I guess intensity values are dropped when the point cloud is downsampled with pcl::Octtree.
https://github.com/koide3/hdl_graph_slam/blob/b97e2c1ab4877f2e9c89033b3f3f4d284940dd62/src/hdl_graph_slam/map_cloud_generator.cpp#L42

Maybe by changing this downsampling method, you can have a point clouds with intensities.

**Comment by HappySamuel** [comment]
Hi @donrv 

I just found out an alternative way to same the pointcloud with intensity. But there is a pre-requistie for doing so. The generated pointcloud especially for mapping use must originally contain intensity values.

Then, you can try the following:

![Screenshot from 2019-03-21 10-04-19](https://user-images.githubusercontent.com/18137963/54732241-b2b38880-4bcd-11e9-874d-9081020ae385.png)

Hope my experience can help you.

Samuel
