### ISSUE TITLE
Where to find the hdl_graph_slam/SaveMap.h ??

### ISSUE THREAD

**Issue by HappySamuel** [koide3/hdl_graph_slam#53]
Hi,

I am curious where can i find this file (SaveMap.h). I have been searching it in all the directories, but i couldn't find them. I need to customize it for my own usage.

Best.
Samuel

**Comment by koide3** [comment]
Hi @HappySamuel ,

The header file will be generated by catkin automatically. Once you do catkin_make, you should be able to find it in /your/catkin_ws/devel/include/hdl_graph_slam

**Comment by HappySamuel** [comment]
Hi @koide3 

Yeah, i found it. Thank you very much. By the way, i found an alternative way to save the PointCloud map. It's through pcl_ros package with command as figure below:

![Screenshot from 2019-03-21 10-04-19](https://user-images.githubusercontent.com/18137963/54729873-c99fae00-4bc0-11e9-8ed8-1bbe83efbfe1.png)
