### ISSUE TITLE
can you give me your paper?

### ISSUE THREAD

**Issue by Liying0824** [koide3/hdl_graph_slam#6]
Hi，koide:

   I'm learning your open source code of hdl_graph_slam， can you give me your paper (Kenji Koide, Jun Miura, and Emanuele Menegatti, A Portable 3D LIDAR-based System for Long-term and Wide-area People Behavior Measurement, IEEE Transactions on Human-Machine Systems)?My e-mail is 85680757@qq.com
   I promise not to be used for commercial purposes, but for learning.Thanks very much.

Yours
LiYing

**Comment by koide3** [comment]
Hi @Liying0824 ,
Please see the mail I sent you.

**Comment by Liying0824** [comment]
Hi @koide3 ,
Thank you very much.

**Comment by frontw** [comment]
Hi!

Could you send your paper to me too? frontwise@gmail.com

Thanks!

**Comment by sathya1995** [comment]
Hello @koide3 , 

I am very much interested to read your paper. Can you please send me the same to the following mail address : skasturirangan@wpi.edu  ?

Thanks a lot. 

Regards, 
Sathya Narayanan K

**Comment by sysuequal** [comment]
Hello!
Could you send your paper to me too? I am learning about the 3D Lidar slam.
My email is dengyq28@mail2.sysu.edu.cn
Thanks

**Comment by sunmiaozju** [comment]
Hello @koide3 ,

could you send your paper to me ,too? I am also interested in your work about 3D slam.
My email address is [sun_miao@zju.edu.cn](url)
Thanks a lot!

**Comment by koide3** [comment]
Hi guys,
Please do NOT request the paper at this issue since I do not check CLOSED issues usually. In case you need the paper, send a mail to koide@aisl.cs.tut.ac.jp from your official address in your institute or organization.

**Comment by lliuguangwei** [comment]
Hi @koide3  ,

I ran your code and achieved good results. Could you send your paper to me?
My email address is 285265661@qq.com

Regards,
Guangwei.Liu

**Comment by yoyoyin0902** [comment]
Could you send your paper to me?
My email address is amy0937968@gmail.com
Thank you so much~
