### ISSUE TITLE
KITTI Dataset

### ISSUE THREAD

**Issue by mnik17** [koide3/hdl_graph_slam#64]
Hello,

Edit: Originally I opened the issue for another problem, but I fixed it.

So I'm trying to test the algorithm on the KITTI Dataset, and more specifically the odometry data, and I already have the data in a rosbag file. Could you please explain how should I go about it? I suppose I should use the hdl_graph_slam_kit.launch, but when I do I still cannot see the point cloud in rviz. Any help is appreciated.  

Cheers

**Comment by mhaboali** [comment]
Hi @mnik17 

Have you succeeded to get it working with KITTI odometry dataset?

Please let us know how did you manage to run it?

Thanks so much!
