### ISSUE TITLE
why the gps_edge_stddev_xy is higher than gps_edge_stddev_z ?

### ISSUE THREAD

**Issue by sume-cn** [koide3/hdl_graph_slam#70]
normally the confidence of gps in plane is higher than in altitude.

**Comment by koide3** [comment]
For a specific trial, we needed to constrain the altitude deviation, and put a high weight for the altitude observations. But, yes, in general, altitude data may have larger errors. Please tune the parameters for your purpose.

**Comment by sume-cn** [comment]
got it, thanks!
