### ISSUE TITLE
when enable_imu_ori = true,  sometimes trajectory has sudden change and deviation increasingly, why ?

### ISSUE THREAD

**Issue by chennuo0125** [koide3/hdl_graph_slam#78]
deviation video :  
[hdl_slip.zip](https://github.com/koide3/hdl_graph_slam/files/3707855/hdl_slip.zip)  
actual environment (red region) :  
![yungu_all](https://user-images.githubusercontent.com/37269147/66490705-2a062680-eae4-11e9-860e-9d1a267d8955.png)  
  
  
phenomenon:  
        i have test some times, i found that this deviation just happen when the yaw angle difference between current pose and initial pose is 3.141592654(pi), i dont konw why ?

**Comment by chennuo0125** [comment]
in addition to above phenomenon, i also found that deviation happen when the first pose of trajectory is zero (roll=0, pitch=0, yaw=0)

**Comment by koide3** [comment]
Hi @chennuo0125 ,
It seems it's a bug of the orientation error calculation. Could you try to change the following like:

https://github.com/koide3/hdl_graph_slam/blob/e5f8b271b29b1b75e242f621d8ea22e019008802/include/g2o/edge_se3_priorquat.hpp#L19

to:
```cpp
if(Eigen::Quaterniond(v1->estimate().linear()).coeffs().dot(estimate.coeffs()) < 0.0) {
  estimate.coeffs() = -estimate.coeffs();
}
```

The current implementation checks if LIDAR and IMU orientation axes match together in a wrong way. The fixed version would properly handle flipped rotation axes.

**Comment by chennuo0125** [comment]
void computeError() override {
			const g2o::VertexSE3* v1 = static_cast<const g2o::VertexSE3*>(_vertices[0]);

			Eigen::Quaterniond estimate = Eigen::Quaterniond(v1->estimate().linear());
			// if(estimate.w() < 0) {
			// 	estimate.coeffs() = -estimate.coeffs();
			// }
			if(Eigen::Quaterniond(v1->estimate().linear()).coeffs().dot(estimate.coeffs()) < 0.0) {
			  estimate.coeffs() = -estimate.coeffs();
			}
			_error = estimate.vec() - _measurement.vec();
		}  
i have change code as you recommanded, but i encounter same flip problem, why?  
flip video :  
[flip2.zip](https://github.com/koide3/hdl_graph_slam/files/3711833/flip2.zip)

**Comment by chennuo0125** [comment]
only position of arise flip problem is changed ......

**Comment by koide3** [comment]
Could you try the following code:
```cpp
if(_measurement.coeffs().dot(estimate.coeffs()) < 0.0) {
  estimate.coeffs() = -estimate.coeffs();
}
```

**Comment by chennuo0125** [comment]
it's ok :+1: , thank you
