### ISSUE TITLE
start pose far away from map frame ???

### ISSUE THREAD

**Issue by chennuo0125** [koide3/hdl_graph_slam#80]
![first_pose_no_fixed](https://user-images.githubusercontent.com/37269147/66659269-c3187700-ec75-11e9-8403-8cff2e932df3.png)
  
https://github.com/koide3/hdl_graph_slam/blob/e5f8b271b29b1b75e242f621d8ea22e019008802/apps/hdl_graph_slam_nodelet.cpp#L203  
above code has fixed first pose, why start pose far away from map frame ???

**Comment by koide3** [comment]
Hi @chennuo0125 ,
The code just above that line decides if the first node is fixed.
https://github.com/koide3/hdl_graph_slam/blob/e5f8b271b29b1b75e242f621d8ea22e019008802/apps/hdl_graph_slam_nodelet.cpp#L201

Make "fix_first_node" in the launch file true to enable fixing the fist node.

**Comment by chennuo0125** [comment]
oh sorry, i didnt see it clearly, thank you very much :) :) :)
