### ISSUE TITLE
map drift a lot,loop not found

### ISSUE THREAD

**Issue by liuyf5231** [koide3/hdl_graph_slam#89]
Hi koide3 ,

I tested hdl graph slam by robosense 16 lidar, but i found that there is something wrong with the map. 

```
--- loop detection ---
num_candidates: 8
matching........ done
best_score: 36.815    time: 0.000[sec]
loop not found...
```

tf between map and odom, 

```
At time 1572313024.112
- Translation: [-5.383, -2.814, 16.107]
- Rotation: in Quaternion [-0.001, -0.031, -0.034, 0.999]
            in RPY (radian) [-0.001, -0.062, -0.068]
            in RPY (degree) [-0.034, -3.564, -3.881]
```

**Comment by liuyf5231** [comment]
![1](https://user-images.githubusercontent.com/47884441/67742302-a55d5700-fa56-11e9-8c4a-b0bcfac7e515.png)

**Comment by liuyf5231** [comment]
![2](https://user-images.githubusercontent.com/47884441/67742313-b0b08280-fa56-11e9-9cb1-c9add40183ca.png)

**Comment by koide3** [comment]
Hi @liuyf5231 ,
NDT-based methods may not work well with 16-line LIDARs because it is not very robust to sparse point clouds. Could you try to use GICP or GICP_OMP instead of NDT_OMP (by changing parameters in the launch file)? If you are using ROS melodic, GICP should work well (PCL on Kinetic or earlier has a bug). You can also try to slow down the rosbag playback speed:
```bash rosbag play --clock -r 0.2 bagfilename.bag```

**Comment by liuyf5231** [comment]
> Hi @liuyf5231 ,
> NDT-based methods may not work well with 16-line LIDARs because it is not very robust to sparse point clouds. Could you try to use GICP or GICP_OMP instead of NDT_OMP (by changing parameters in the launch file)? If you are using ROS melodic, GICP should work well (PCL on Kinetic or earlier has a bug). You can also try to slow down the rosbag playback speed:
> `bash rosbag play --clock -r 0.2 bagfilename.bag`

ok, I will try.

**Comment by koide3** [comment]
In that case, maybe you can use NDT_OMP since the target point cloud (map cloud) is dense.
