### ISSUE TITLE
Map is not saved correctly

### ISSUE THREAD

**Issue by ricber** [koide3/hdl_graph_slam#95]
Hi, 
I'm testing hdl with my own data. When I do the mapping with `hdl_graph_slam` the map is correctly showed parallel to the ground.
![Screenshot from 2019-12-03 15-24-28](https://user-images.githubusercontent.com/18362950/70060170-4a34fc00-15e2-11ea-85f6-b1f1cf2d91cc.png)
 
Then, I call the `save_map` service to obtain the pcd file. However, the saved map is no more correctly referenced to the `map` frame but it has a weird rotation and translation.
![Screenshot from 2019-12-03 15-26-53](https://user-images.githubusercontent.com/18362950/70060267-7ea8b800-15e2-11ea-8f51-1d5414bff015.png)

Do you know what's causing the problem? I'm just using the `velodyne_points` data, no GPS, no IMU or anything else (ground detection is enabled).

Thanks.

**Comment by koide3** [comment]
Hi @ricber ,
Do you see the same problem if you open the PCD with some point cloud viewers (e.g., pcl_viewer or CloudCompare)?

**Comment by ricber** [comment]
Yep, I see the same problem with the pcl_viewer

On 4 Dec 2019, at 02:22, koide3 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @ricber<https://github.com/ricber> ,
Do you see the same problem if you open the PCD with some point cloud viewers (e.g., pcl_viewer or CloudCompare)?

**Comment by ricber** [comment]
Yep, I see the same problem with the pcl_viewer.

**EDIT:** I tried again but I cannot reproduce the error. I don't know what happened at that time. I close the issue. Thank you anyway :)

**Comment by ricber** [comment]
Actually, the problem is solved by setting the `enable_floor_detection` to true. If I emove the ground plane constraint, the problem is still there. Do you have any idea?

**Comment by ricber** [comment]
Closed because of #113
